name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy-page:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # Checkout the repository
      - name: Setup Hugo # Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.109.0"
          extended: true
      - name: Build
        run: hugo --minify --debug
      - name: List files
        run: ls -l ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
