name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy-page:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Checkout the repository
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo # Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.135.0"
          extended: true
      - name: Build
        run: hugo --minify --logLevel debug
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: beer.blog.castrillon.ch
